### ISSUE TITLE
Add doc comments as description to fields

### ISSUE THREAD

**Issue by auctumnus** [valentinpalkovic/prisma-json-schema-generator#326]
The Prisma schema [defines triple-slash comments to be used for documentation](https://www.prisma.io/docs/concepts/components/prisma-schema#comments). Would it be possible to put doc comments for a property/model into the JSON schema `description` field?

Ideally this could also be used in extending the docs a bit - e.g. an `@internal` doc marker like JSDoc to prevent a property from being put into the resulting JSON schema. That might be better addressed in another issue though.

**Comment by valentinpalkovic** [comment]
@auctumnus Thank you for creating the issue! This should definitely work. I will try to implement this directly tomorrow!

I will let you know as soon as I have implemented and released a new version.
