### ISSUE TITLE
Error: Generator at prisma-json-schema-generator could not start

### ISSUE THREAD

**Issue by MarleyDabb** [valentinpalkovic/prisma-json-schema-generator#36]
Hi I keep getting the following error when attempting to run 'prisma generator'

`Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Generator at prisma-json-schema-generator could not start:

/bin/sh: prisma-json-schema-generator: command not found

`

Here's my schema 

`
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Make sure you run 'prisma generate' in the CLI to generate the schema. *note* prisma CLI needed

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator jsonSchema {
  provider = "prisma-json-schema-generator"
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

model Post {
    id String @id @default(dbgenerated()) @map("_id") @db.ObjectId
    slug String
    title String
    body String
}

`

**Comment by valentinpalkovic** [comment]
Can you tell me which prisma and node version do you use?

**Comment by valentinpalkovic** [comment]
@MarleyDabb Please reopen the issue and add further information, if you still have any problems.

**Comment by psecuresystem** [comment]
@MarleyDabb I'm facing the error. Did you fix it?
