### ISSUE TITLE
Error with BigInt

### ISSUE THREAD

**Issue by marcelinhov2** [valentinpalkovic/prisma-json-schema-generator#37]
Hi, I'm trying to use a BigInt field in my project but when I run `prisma generate` I'm getting the following error:

![image](https://user-images.githubusercontent.com/232648/127379909-76dec949-6533-4942-9a4c-d40954294297.png)

I guess this is something that should be added here maybe: https://github.com/valentinpalkovic/prisma-json-schema-generator/blob/1322ae8f076a711fb0ea93f3a0505fb1daa22132/src/generator/helpers.ts#L3

Thank you.

**Comment by marcelinhov2** [comment]
hello?

**Comment by valentinpalkovic** [comment]
Hi @marcelinhov2.

BigInt was introduced in prisma 2.11.0 together with `Bytes` and `Decimal`. I will provide a fix for your issue
