### ISSUE TITLE
Required properties field

### ISSUE THREAD

**Issue by nklisch** [valentinpalkovic/prisma-json-schema-generator#577]
I would like the following option for the Schema generation:

When a field is not nullable in prisma schema, make it required in the JSON schema.
This prevents cases where the JSON schema validates JSON as valid, but prisma will not accept the JSON as valid data because a non-nullable field is required.

Of course, if there is a default option on the prisma schema, it should not be added to the required array.

**Comment by nklisch** [comment]
I wanted to give an explicit example of why it is more work to not provide the required field, and remove/modify it when needed.

Imagine migrating the schema to add a new field. This new field is required for create requests, but not patch requests.

In this case, if required was not included, and I wanted the validation before sending it prisma, I would have to go through every route and add that new field to my required, which could both be time-consuming and error-prone, not to mention likely forgotten.

If the required property is included, then  I can simply remove the required for my patch requests, and change nothing for my other requests.

**Comment by valentinpalkovic** [comment]
Valid points! Especially, if we make the generation of required fields optional, everyone can decide how to deal with the generated JSON Schema. I have nothing against introducing this configurable feature!

**Comment by valentinpalkovic** [comment]
:tada: This issue is fixed in version 3.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/prisma-json-schema-generator/v/3.0.0)
- [GitHub release](https://github.com/valentinpalkovic/prisma-json-schema-generator/releases/tag/v3.0.0)
