### ISSUE TITLE
Missing $id in generated json-schema

### ISSUE THREAD

**Issue by FabioReact** [valentinpalkovic/prisma-json-schema-generator#73]
Hi,

I was looking to add/modify validations rules, and found an issue about it [here](https://github.com/valentinpalkovic/prisma-json-schema-generator/issues/13). I do agree with your choice of keeping it away from this library. It is also quite easy to use $[ref](https://ajv.js.org/guide/combining-schemas.html#a-name-ref-a-combining-schemas-with-ref) to do the job. But to do that, the original json-schema must have an $id to reference it. 

Is it ok if i open a PR to fix it (along with the test)?

Thanks @valentinpalkovic

**Comment by valentinpalkovic** [comment]
Hey @FabioReact!

Thank you for opening this issue. Can you explain a bit further, how the generated JSON schema should look like after your changes? I would like to understand what your exact proposal is!

**Comment by FabioReact** [comment]
It should only add a new key/value pair, such as:
`{
  "$id": "prisma-json-schema",
  "$schema": "http://json-schema.org/draft-07/schema#"
  ...
}
`
That way, each time you generate from a new prisma schema, you will keep the $id in json-schema.json in order to make a reference to it if needed.
