### ISSUE TITLE
Union types with `anyOf` instead of array

### ISSUE THREAD

**Issue by JulianCataldo** [valentinpalkovic/prisma-json-schema-generator#874]
Hello :)

It seems like

```json
"type": ["string", "null"]
```

would be better off with:

```json
{
  "anyOf": [
    {
      "type": "string"
    },
    {
      "type": "null"
    },
  ]
}
```

As AJV docs specifies: https://ajv.js.org/strict-mode.html#strict-types

Stemming from this issue:
https://github.com/seriousme/fastify-openapi-glue/issues/445#issuecomment-1373437908

Any specific reason for this format (I never encountered it before TBH)?

Thanks for your work.

**Comment by valentinpalkovic** [comment]
@JulianCataldo Interested in opening a PR? :)

**Comment by JulianCataldo** [comment]
When I'll go back to the project using it, I'll try to hack the generator internals a bit, to see.
